/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SculpturesIndexRouteImport } from './routes/sculptures/index'
import { Route as PeinturesIndexRouteImport } from './routes/peintures/index'
import { Route as DessinsIndexRouteImport } from './routes/dessins/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AdminSculpturesRouteImport } from './routes/admin/sculptures'
import { Route as AdminPresentationRouteImport } from './routes/admin/presentation'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminPeinturesRouteImport } from './routes/admin/peintures'
import { Route as AdminMetaRouteImport } from './routes/admin/meta'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminDessinsRouteImport } from './routes/admin/dessins'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as SculpturesCategorieCategoryKeyRouteImport } from './routes/sculptures/categorie.$categoryKey'
import { Route as SculpturesAnneeYearRouteImport } from './routes/sculptures/annee.$year'
import { Route as PeinturesCategorieCategoryKeyRouteImport } from './routes/peintures/categorie.$categoryKey'
import { Route as PeinturesAnneeYearRouteImport } from './routes/peintures/annee.$year'
import { Route as DessinsCategorieCategoryKeyRouteImport } from './routes/dessins/categorie.$categoryKey'
import { Route as DessinsAnneeYearRouteImport } from './routes/dessins/annee.$year'
import { Route as ImagesLibraryChar123FolderChar125FilenameRouteImport } from './routes/images/$library.{-$folder}.$filename'

const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SculpturesIndexRoute = SculpturesIndexRouteImport.update({
  id: '/sculptures/',
  path: '/sculptures/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeinturesIndexRoute = PeinturesIndexRouteImport.update({
  id: '/peintures/',
  path: '/peintures/',
  getParentRoute: () => rootRouteImport,
} as any)
const DessinsIndexRoute = DessinsIndexRouteImport.update({
  id: '/dessins/',
  path: '/dessins/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const AdminSculpturesRoute = AdminSculpturesRouteImport.update({
  id: '/sculptures',
  path: '/sculptures',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPresentationRoute = AdminPresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPeinturesRoute = AdminPeinturesRouteImport.update({
  id: '/peintures',
  path: '/peintures',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMetaRoute = AdminMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDessinsRoute = AdminDessinsRouteImport.update({
  id: '/dessins',
  path: '/dessins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SculpturesCategorieCategoryKeyRoute =
  SculpturesCategorieCategoryKeyRouteImport.update({
    id: '/sculptures/categorie/$categoryKey',
    path: '/sculptures/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const SculpturesAnneeYearRoute = SculpturesAnneeYearRouteImport.update({
  id: '/sculptures/annee/$year',
  path: '/sculptures/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const PeinturesCategorieCategoryKeyRoute =
  PeinturesCategorieCategoryKeyRouteImport.update({
    id: '/peintures/categorie/$categoryKey',
    path: '/peintures/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeinturesAnneeYearRoute = PeinturesAnneeYearRouteImport.update({
  id: '/peintures/annee/$year',
  path: '/peintures/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const DessinsCategorieCategoryKeyRoute =
  DessinsCategorieCategoryKeyRouteImport.update({
    id: '/dessins/categorie/$categoryKey',
    path: '/dessins/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const DessinsAnneeYearRoute = DessinsAnneeYearRouteImport.update({
  id: '/dessins/annee/$year',
  path: '/dessins/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesLibraryChar123FolderChar125FilenameRoute =
  ImagesLibraryChar123FolderChar125FilenameRouteImport.update({
    id: '/images/$library/{-$folder}/$filename',
    path: '/images/$library/{-$folder}/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dessins': typeof AdminDessinsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/peintures': typeof AdminPeinturesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/presentation': typeof AdminPresentationRoute
  '/admin/sculptures': typeof AdminSculpturesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dessins/': typeof DessinsIndexRoute
  '/peintures/': typeof PeinturesIndexRoute
  '/sculptures/': typeof SculpturesIndexRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dessins': typeof AdminDessinsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/peintures': typeof AdminPeinturesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/presentation': typeof AdminPresentationRoute
  '/admin/sculptures': typeof AdminSculpturesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/dessins': typeof DessinsIndexRoute
  '/peintures': typeof PeinturesIndexRoute
  '/sculptures': typeof SculpturesIndexRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/dessins': typeof AdminDessinsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/peintures': typeof AdminPeinturesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/presentation': typeof AdminPresentationRoute
  '/admin/sculptures': typeof AdminSculpturesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dessins/': typeof DessinsIndexRoute
  '/peintures/': typeof PeinturesIndexRoute
  '/sculptures/': typeof SculpturesIndexRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/posts'
    | '/presentation'
    | '/admin/contact'
    | '/admin/dessins'
    | '/admin/home'
    | '/admin/meta'
    | '/admin/peintures'
    | '/admin/posts'
    | '/admin/presentation'
    | '/admin/sculptures'
    | '/posts/$postId'
    | '/admin/'
    | '/dessins/'
    | '/peintures/'
    | '/sculptures/'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/posts'
    | '/presentation'
    | '/admin/contact'
    | '/admin/dessins'
    | '/admin/home'
    | '/admin/meta'
    | '/admin/peintures'
    | '/admin/posts'
    | '/admin/presentation'
    | '/admin/sculptures'
    | '/posts/$postId'
    | '/admin'
    | '/dessins'
    | '/peintures'
    | '/sculptures'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/posts'
    | '/presentation'
    | '/admin/contact'
    | '/admin/dessins'
    | '/admin/home'
    | '/admin/meta'
    | '/admin/peintures'
    | '/admin/posts'
    | '/admin/presentation'
    | '/admin/sculptures'
    | '/posts/$postId'
    | '/admin/'
    | '/dessins/'
    | '/peintures/'
    | '/sculptures/'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRouteWithChildren
  PresentationRoute: typeof PresentationRoute
  DessinsIndexRoute: typeof DessinsIndexRoute
  PeinturesIndexRoute: typeof PeinturesIndexRoute
  SculpturesIndexRoute: typeof SculpturesIndexRoute
  DessinsAnneeYearRoute: typeof DessinsAnneeYearRoute
  DessinsCategorieCategoryKeyRoute: typeof DessinsCategorieCategoryKeyRoute
  PeinturesAnneeYearRoute: typeof PeinturesAnneeYearRoute
  PeinturesCategorieCategoryKeyRoute: typeof PeinturesCategorieCategoryKeyRoute
  SculpturesAnneeYearRoute: typeof SculpturesAnneeYearRoute
  SculpturesCategorieCategoryKeyRoute: typeof SculpturesCategorieCategoryKeyRoute
  ImagesLibraryChar123FolderChar125FilenameRoute: typeof ImagesLibraryChar123FolderChar125FilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures/': {
      id: '/sculptures/'
      path: '/sculptures'
      fullPath: '/sculptures/'
      preLoaderRoute: typeof SculpturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peintures/': {
      id: '/peintures/'
      path: '/peintures'
      fullPath: '/peintures/'
      preLoaderRoute: typeof PeinturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/': {
      id: '/dessins/'
      path: '/dessins'
      fullPath: '/dessins/'
      preLoaderRoute: typeof DessinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/admin/sculptures': {
      id: '/admin/sculptures'
      path: '/sculptures'
      fullPath: '/admin/sculptures'
      preLoaderRoute: typeof AdminSculpturesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/presentation': {
      id: '/admin/presentation'
      path: '/presentation'
      fullPath: '/admin/presentation'
      preLoaderRoute: typeof AdminPresentationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/peintures': {
      id: '/admin/peintures'
      path: '/peintures'
      fullPath: '/admin/peintures'
      preLoaderRoute: typeof AdminPeinturesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/meta': {
      id: '/admin/meta'
      path: '/meta'
      fullPath: '/admin/meta'
      preLoaderRoute: typeof AdminMetaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dessins': {
      id: '/admin/dessins'
      path: '/dessins'
      fullPath: '/admin/dessins'
      preLoaderRoute: typeof AdminDessinsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sculptures/categorie/$categoryKey': {
      id: '/sculptures/categorie/$categoryKey'
      path: '/sculptures/categorie/$categoryKey'
      fullPath: '/sculptures/categorie/$categoryKey'
      preLoaderRoute: typeof SculpturesCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures/annee/$year': {
      id: '/sculptures/annee/$year'
      path: '/sculptures/annee/$year'
      fullPath: '/sculptures/annee/$year'
      preLoaderRoute: typeof SculpturesAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peintures/categorie/$categoryKey': {
      id: '/peintures/categorie/$categoryKey'
      path: '/peintures/categorie/$categoryKey'
      fullPath: '/peintures/categorie/$categoryKey'
      preLoaderRoute: typeof PeinturesCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peintures/annee/$year': {
      id: '/peintures/annee/$year'
      path: '/peintures/annee/$year'
      fullPath: '/peintures/annee/$year'
      preLoaderRoute: typeof PeinturesAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/categorie/$categoryKey': {
      id: '/dessins/categorie/$categoryKey'
      path: '/dessins/categorie/$categoryKey'
      fullPath: '/dessins/categorie/$categoryKey'
      preLoaderRoute: typeof DessinsCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/annee/$year': {
      id: '/dessins/annee/$year'
      path: '/dessins/annee/$year'
      fullPath: '/dessins/annee/$year'
      preLoaderRoute: typeof DessinsAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$library/{-$folder}/$filename': {
      id: '/images/$library/{-$folder}/$filename'
      path: '/images/$library/{-$folder}/$filename'
      fullPath: '/images/$library/{-$folder}/$filename'
      preLoaderRoute: typeof ImagesLibraryChar123FolderChar125FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContactRoute: typeof AdminContactRoute
  AdminDessinsRoute: typeof AdminDessinsRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminMetaRoute: typeof AdminMetaRoute
  AdminPeinturesRoute: typeof AdminPeinturesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminPresentationRoute: typeof AdminPresentationRoute
  AdminSculpturesRoute: typeof AdminSculpturesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContactRoute: AdminContactRoute,
  AdminDessinsRoute: AdminDessinsRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminMetaRoute: AdminMetaRoute,
  AdminPeinturesRoute: AdminPeinturesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminPresentationRoute: AdminPresentationRoute,
  AdminSculpturesRoute: AdminSculpturesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRouteWithChildren,
  PresentationRoute: PresentationRoute,
  DessinsIndexRoute: DessinsIndexRoute,
  PeinturesIndexRoute: PeinturesIndexRoute,
  SculpturesIndexRoute: SculpturesIndexRoute,
  DessinsAnneeYearRoute: DessinsAnneeYearRoute,
  DessinsCategorieCategoryKeyRoute: DessinsCategorieCategoryKeyRoute,
  PeinturesAnneeYearRoute: PeinturesAnneeYearRoute,
  PeinturesCategorieCategoryKeyRoute: PeinturesCategorieCategoryKeyRoute,
  SculpturesAnneeYearRoute: SculpturesAnneeYearRoute,
  SculpturesCategorieCategoryKeyRoute: SculpturesCategorieCategoryKeyRoute,
  ImagesLibraryChar123FolderChar125FilenameRoute:
    ImagesLibraryChar123FolderChar125FilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
