/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SculpturesIndexRouteImport } from './routes/sculptures/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PeinturesIndexRouteImport } from './routes/peintures/index'
import { Route as DessinsIndexRouteImport } from './routes/dessins/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as SculpturesCategorieCategoryKeyRouteImport } from './routes/sculptures/categorie.$categoryKey'
import { Route as SculpturesAnneeYearRouteImport } from './routes/sculptures/annee.$year'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as PeinturesCategorieCategoryKeyRouteImport } from './routes/peintures/categorie.$categoryKey'
import { Route as PeinturesAnneeYearRouteImport } from './routes/peintures/annee.$year'
import { Route as DessinsCategorieCategoryKeyRouteImport } from './routes/dessins/categorie.$categoryKey'
import { Route as DessinsAnneeYearRouteImport } from './routes/dessins/annee.$year'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as ImagesLibraryChar123FolderChar125FilenameRouteImport } from './routes/images/$library.{-$folder}.$filename'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SculpturesIndexRoute = SculpturesIndexRouteImport.update({
  id: '/sculptures/',
  path: '/sculptures/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PeinturesIndexRoute = PeinturesIndexRouteImport.update({
  id: '/peintures/',
  path: '/peintures/',
  getParentRoute: () => rootRouteImport,
} as any)
const DessinsIndexRoute = DessinsIndexRouteImport.update({
  id: '/dessins/',
  path: '/dessins/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const SculpturesCategorieCategoryKeyRoute =
  SculpturesCategorieCategoryKeyRouteImport.update({
    id: '/sculptures/categorie/$categoryKey',
    path: '/sculptures/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const SculpturesAnneeYearRoute = SculpturesAnneeYearRouteImport.update({
  id: '/sculptures/annee/$year',
  path: '/sculptures/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const PeinturesCategorieCategoryKeyRoute =
  PeinturesCategorieCategoryKeyRouteImport.update({
    id: '/peintures/categorie/$categoryKey',
    path: '/peintures/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeinturesAnneeYearRoute = PeinturesAnneeYearRouteImport.update({
  id: '/peintures/annee/$year',
  path: '/peintures/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const DessinsCategorieCategoryKeyRoute =
  DessinsCategorieCategoryKeyRouteImport.update({
    id: '/dessins/categorie/$categoryKey',
    path: '/dessins/categorie/$categoryKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const DessinsAnneeYearRoute = DessinsAnneeYearRouteImport.update({
  id: '/dessins/annee/$year',
  path: '/dessins/annee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const ImagesLibraryChar123FolderChar125FilenameRoute =
  ImagesLibraryChar123FolderChar125FilenameRouteImport.update({
    id: '/images/$library/{-$folder}/$filename',
    path: '/images/$library/{-$folder}/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dessins/': typeof DessinsIndexRoute
  '/peintures/': typeof PeinturesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/sculptures/': typeof SculpturesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/dessins': typeof DessinsIndexRoute
  '/peintures': typeof PeinturesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/sculptures': typeof SculpturesIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dessins/': typeof DessinsIndexRoute
  '/peintures/': typeof PeinturesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/sculptures/': typeof SculpturesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dessins/annee/$year': typeof DessinsAnneeYearRoute
  '/dessins/categorie/$categoryKey': typeof DessinsCategorieCategoryKeyRoute
  '/peintures/annee/$year': typeof PeinturesAnneeYearRoute
  '/peintures/categorie/$categoryKey': typeof PeinturesCategorieCategoryKeyRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/sculptures/annee/$year': typeof SculpturesAnneeYearRoute
  '/sculptures/categorie/$categoryKey': typeof SculpturesCategorieCategoryKeyRoute
  '/images/$library/{-$folder}/$filename': typeof ImagesLibraryChar123FolderChar125FilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/deferred'
    | '/login'
    | '/posts'
    | '/presentation'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/admin/'
    | '/dessins/'
    | '/peintures/'
    | '/posts/'
    | '/sculptures/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/users/$userId'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/posts/$postId/deep'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/deferred'
    | '/login'
    | '/presentation'
    | '/redirect'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/admin'
    | '/dessins'
    | '/peintures'
    | '/posts'
    | '/sculptures'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/users/$userId'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/posts/$postId/deep'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/contact'
    | '/deferred'
    | '/login'
    | '/posts'
    | '/presentation'
    | '/redirect'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/admin/'
    | '/dessins/'
    | '/peintures/'
    | '/posts/'
    | '/sculptures/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/users/$userId'
    | '/dessins/annee/$year'
    | '/dessins/categorie/$categoryKey'
    | '/peintures/annee/$year'
    | '/peintures/categorie/$categoryKey'
    | '/posts_/$postId/deep'
    | '/sculptures/annee/$year'
    | '/sculptures/categorie/$categoryKey'
    | '/images/$library/{-$folder}/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeferredRoute: typeof DeferredRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRouteWithChildren
  PresentationRoute: typeof PresentationRoute
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  DessinsIndexRoute: typeof DessinsIndexRoute
  PeinturesIndexRoute: typeof PeinturesIndexRoute
  SculpturesIndexRoute: typeof SculpturesIndexRoute
  DessinsAnneeYearRoute: typeof DessinsAnneeYearRoute
  DessinsCategorieCategoryKeyRoute: typeof DessinsCategorieCategoryKeyRoute
  PeinturesAnneeYearRoute: typeof PeinturesAnneeYearRoute
  PeinturesCategorieCategoryKeyRoute: typeof PeinturesCategorieCategoryKeyRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
  SculpturesAnneeYearRoute: typeof SculpturesAnneeYearRoute
  SculpturesCategorieCategoryKeyRoute: typeof SculpturesCategorieCategoryKeyRoute
  ImagesLibraryChar123FolderChar125FilenameRoute: typeof ImagesLibraryChar123FolderChar125FilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/sculptures/': {
      id: '/sculptures/'
      path: '/sculptures'
      fullPath: '/sculptures/'
      preLoaderRoute: typeof SculpturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/peintures/': {
      id: '/peintures/'
      path: '/peintures'
      fullPath: '/peintures/'
      preLoaderRoute: typeof PeinturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/': {
      id: '/dessins/'
      path: '/dessins'
      fullPath: '/dessins/'
      preLoaderRoute: typeof DessinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/sculptures/categorie/$categoryKey': {
      id: '/sculptures/categorie/$categoryKey'
      path: '/sculptures/categorie/$categoryKey'
      fullPath: '/sculptures/categorie/$categoryKey'
      preLoaderRoute: typeof SculpturesCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculptures/annee/$year': {
      id: '/sculptures/annee/$year'
      path: '/sculptures/annee/$year'
      fullPath: '/sculptures/annee/$year'
      preLoaderRoute: typeof SculpturesAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peintures/categorie/$categoryKey': {
      id: '/peintures/categorie/$categoryKey'
      path: '/peintures/categorie/$categoryKey'
      fullPath: '/peintures/categorie/$categoryKey'
      preLoaderRoute: typeof PeinturesCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peintures/annee/$year': {
      id: '/peintures/annee/$year'
      path: '/peintures/annee/$year'
      fullPath: '/peintures/annee/$year'
      preLoaderRoute: typeof PeinturesAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/categorie/$categoryKey': {
      id: '/dessins/categorie/$categoryKey'
      path: '/dessins/categorie/$categoryKey'
      fullPath: '/dessins/categorie/$categoryKey'
      preLoaderRoute: typeof DessinsCategorieCategoryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dessins/annee/$year': {
      id: '/dessins/annee/$year'
      path: '/dessins/annee/$year'
      fullPath: '/dessins/annee/$year'
      preLoaderRoute: typeof DessinsAnneeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/images/$library/{-$folder}/$filename': {
      id: '/images/$library/{-$folder}/$filename'
      path: '/images/$library/{-$folder}/$filename'
      fullPath: '/images/$library/{-$folder}/$filename'
      preLoaderRoute: typeof ImagesLibraryChar123FolderChar125FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DeferredRoute: DeferredRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRouteWithChildren,
  PresentationRoute: PresentationRoute,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  DessinsIndexRoute: DessinsIndexRoute,
  PeinturesIndexRoute: PeinturesIndexRoute,
  SculpturesIndexRoute: SculpturesIndexRoute,
  DessinsAnneeYearRoute: DessinsAnneeYearRoute,
  DessinsCategorieCategoryKeyRoute: DessinsCategorieCategoryKeyRoute,
  PeinturesAnneeYearRoute: PeinturesAnneeYearRoute,
  PeinturesCategorieCategoryKeyRoute: PeinturesCategorieCategoryKeyRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
  SculpturesAnneeYearRoute: SculpturesAnneeYearRoute,
  SculpturesCategorieCategoryKeyRoute: SculpturesCategorieCategoryKeyRoute,
  ImagesLibraryChar123FolderChar125FilenameRoute:
    ImagesLibraryChar123FolderChar125FilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
